const GET_PAGE = "GET_PAGE";
const SEND_NEW_TASK = "SEND_NEW_TASK";
const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";

const SET_CURRENT_EDITING_TASK = "SET_CURRENT_EDITING_TASK";
const SAVE_CURRENT_EDITING_TASK = "SAVE_CURRENT_EDITING_TASK";
const END_EDITING = "END_EDITING";
const UPDATE_TASK = "UPDATE_TASK";

const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const CHANGE_MODAL_VISIBILITY = "CHANGE_MODAL_VISIBILITY";
const NEED_AUTHORIZATION = "NEED_AUTHORIZATION";
const CHECK_TOKEN_VALIDATION = "CHECK_TOKEN_VALIDATION";

export {
  GET_PAGE,
  SEND_NEW_TASK,
  START_LOADING,
  STOP_LOADING,
  SET_CURRENT_EDITING_TASK,
  SAVE_CURRENT_EDITING_TASK,
  END_EDITING,
  UPDATE_TASK,
  LOGIN,
  LOGOUT,
  CHANGE_MODAL_VISIBILITY,
  NEED_AUTHORIZATION,
  CHECK_TOKEN_VALIDATION,
};
